//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCKutuphane.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VTKutuphaneEntities2 : DbContext
    {
        public VTKutuphaneEntities2()
            : base("name=VTKutuphaneEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLCeza> TBLCeza { get; set; }
        public virtual DbSet<TBLHareket> TBLHareket { get; set; }
        public virtual DbSet<TBLKasa> TBLKasa { get; set; }
        public virtual DbSet<TBLKategori> TBLKategori { get; set; }
        public virtual DbSet<TBLKitap> TBLKitap { get; set; }
        public virtual DbSet<TBLPersonel> TBLPersonel { get; set; }
        public virtual DbSet<TBLUyeler> TBLUyeler { get; set; }
        public virtual DbSet<TBLYazar> TBLYazar { get; set; }
        public virtual DbSet<TBLHakkimizda> TBLHakkimizda { get; set; }
        public virtual DbSet<TBLiletisim> TBLiletisim { get; set; }
        public virtual DbSet<TBLMesaj> TBLMesaj { get; set; }
        public virtual DbSet<TBLDuyuru> TBLDuyuru { get; set; }
        public virtual DbSet<TBLAdmin> TBLAdmin { get; set; }
    
        public virtual ObjectResult<string> EnFazlaKitapYazar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("EnFazlaKitapYazar");
        }
    
        public virtual ObjectResult<string> EnAktifUye()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("EnAktifUye");
        }
    
        public virtual ObjectResult<string> EnCokOkunanKitap()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("EnCokOkunanKitap");
        }
    
        public virtual ObjectResult<string> EnBasariliPersonel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("EnBasariliPersonel");
        }
    
        public virtual ObjectResult<Nullable<int>> BugunEmanetVerilenK()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("BugunEmanetVerilenK");
        }
    }
}
